#pragma once

#define VOXEL_BLOCK_X_COUNT 10
#define VOXEL_BLOCK_Y_COUNT 10
#define VOXEL_BLOCK_Z_COUNT 256

#define VOXEL_CHUNK_X_COUNT 50
#define VOXEL_CHUNK_Y_COUNT 50
#define VOXEL_CHUNK_Z_COUNT 1

struct VoxelChunk {
	uint16_t typeID[VOXEL_BLOCK_X_COUNT][VOXEL_BLOCK_Y_COUNT][VOXEL_BLOCK_Z_COUNT];
	uint16_t durability[VOXEL_BLOCK_X_COUNT][VOXEL_BLOCK_Y_COUNT][VOXEL_BLOCK_Z_COUNT];
	void *otherData[VOXEL_BLOCK_X_COUNT][VOXEL_BLOCK_Y_COUNT][VOXEL_BLOCK_Z_COUNT];
};

struct VoxelTerrain {
	struct VoxelChunk chunk[VOXEL_CHUNK_X_COUNT][VOXEL_CHUNK_Y_COUNT][VOXEL_CHUNK_Z_COUNT];
};